### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by codewdhruv** [dhrubajyoti89/drowsiness-detection#1]

**Comment by hiteshbhavsar** [comment]
Hello @dhrubajyoti89 , Can you please tell me how can I contribute in this issue as I can't find anything in the description

**Comment by JASKAMAL22** [comment]
Hello @dhrubajyoti89 .I would like to work on this issue. Can you please assigned it to me!!

**Comment by codewdhruv** [comment]
@hiteshbhavsar done

**Comment by codewdhruv** [comment]
@hiteshbhavsar are u still working on the issue?

**Comment by hiteshbhavsar** [comment]
@dhrubajyoti89 yes
