### ISSUE TITLE
I will add name and photo of maintainer in the end of readme file of your repo

### ISSUE THREAD

**Issue by yashlikescode** [dhrubajyoti89/drowsiness-detection#10]
like the one mentioned below
![image](https://user-images.githubusercontent.com/66861659/110197179-cebe9c00-7e6f-11eb-990f-6d6178a5ebc7.png)

**Comment by codewdhruv** [comment]
@kmryashasvi you can do this in the CONTRIBUTORS.md file

**Comment by yashlikescode** [comment]
I will add project maintainer's name in readme file and name of contributors in contributors.md
agree?

**Comment by yashlikescode** [comment]
"Documentation" label is not under crosswoc,
please add labels from one of the labels given below
* Good first issue
* easy
* medium
* hard

**Comment by codewdhruv** [comment]
> I will add project maintainer's name in readme file and name of contributors in contributors.md
> agree?

yes works
