### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by codewdhruv** [dhrubajyoti89/drowsiness-detection#4]

**Comment by Akash20x** [comment]
Can you please assign me this issue as a part of Cross Woc. I would be very happy to do it

**Comment by codewdhruv** [comment]
assigned @Akash20x

**Comment by codewdhruv** [comment]
are u still working on the issue? @Akash20x

**Comment by Akash20x** [comment]
Yes,
It will take some time more to  solve this issue.

**Comment by Akash20x** [comment]
Sorry, I can't figure out the solution for this issue. 
So I withdraw from this issue.
