### ISSUE TITLE
adding banner of crosswoc to the readme

### ISSUE THREAD

**Issue by yashlikescode** [dhrubajyoti89/drowsiness-detection#9]
I will add banner of crosswoc to the readme file of your repo,
also,
I will associate link to crosswoc website to its banner so that, when anyone clicks the crosswoc banner, it will direct them to the website of crosswoc

**Comment by codewdhruv** [comment]
@kmryashasvi ok

**Comment by yashlikescode** [comment]
"Documentation" label is not under crosswoc,
please add labels from one of the labels given below

Good first issue
easy
medium
hard
